LTO_ENABLE = yes
BOOTMAGIC_ENABLE = no
EXTRAKEYS_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
RGBLIGHT_STARTUP_ANIMATION  = no
BACKLIGHT_ENABLE = no

COMBO_ENABLE = yes
VPATH += keyboards/gboards
